### ISSUE TITLE
mission possible part 3, documentation missing module registration

### ISSUE THREAD

**Issue by meandavejustice** [workshopper/goingnative#58]
Documentation appears to be missing this step:

``` c++
NODE_MODULE(addon, Init)
```
Making an issue now, but will come back with a pr when i get an extra moment.

Should this be something mentioned in the prompt for this step? or should it be included in the generated .cc file?

This tripped me up for a bit :/

**Comment by wblankenship** [comment]
Hey @meandavejustice, thanks for opening this issue!

Problem three has a section entitled [Mission: expose the init function to Node.js](https://github.com/workshopper/goingnative/blob/master/exercises/mission_possible_part_three/problem.md#mission-expose-the-init-function-to-nodejs) which contains the following markdown:

```markdown
### Mission: expose the init function to Node.js.

The `Init()` function needs to be given to Node.js because it's the entry-point to the module. Node.js is responsible for passing in the `exports` object. Exposing it to Node.js requires a native Node.js *macro* that does the heavy-lifting of registering your initialization function:

'''c++
NODE_MODULE(modulename, InitFunction)
'''

Where `modulename` matches the name in your *binding.gyp* and your *index.js* and `InitFunction` is the name of your C++ initialization function that accepts the `exports` object.

```

It is possible that section isn't rendering, which would point to a deeper issue. Would you mind checking?

**Comment by meandavejustice** [comment]
@wblankenship the init section is in fact rendering, I must have totally overlooked it. Thank You for your response.
