### ISSUE TITLE
Nan 2.x

### ISSUE THREAD

**Issue by SomeoneWeird** [workshopper/goingnative#59]
Now that Nan 2.x has been released this should probably be updated.

**Comment by rvagg** [comment]
so .. do you think you could do this?

**Comment by SomeoneWeird** [comment]
Potentially. I'll have a look later today :)

**Comment by SomeoneWeird** [comment]
Started https://github.com/SomeoneWeird/goingnative/commit/187dc7eea408b279562647b2c5bd02b52ec13556 - will clean up and PR tomorrow

**Comment by ChALkeR** [comment]
Adding to the list: https://github.com/nodejs/node/issues/2798.

**Comment by SomeoneWeird** [comment]
@ChALkeR PR awaiting merge :)

**Comment by ChALkeR** [comment]
@SomeoneWeird Ok, added the PR too =).

**Comment by julianduque** [comment]
Landed in `goingnative@2.0.0`
