### ISSUE TITLE
Typo in for_the_sake_of_argument/problem.md

### ISSUE THREAD

**Issue by mklaber** [workshopper/goingnative#62]
On line 24 of [for_the_sake_of_argument/problem.md](https://github.com/workshopper/goingnative/blob/master/exercises/for_the_sake_of_argument/problem.md#L24):

> Each element in the array is an object is a V8 type with a special function...

Should read something like

> Each element in the array is an object **which** is a V8 type with a special function

(I'm not super familiar with C++ so my correction may not be accurate, but... I'll leave that up to someone who knows the content better.)

**Comment by julianduque** [comment]
@mklaber a PR is welcome :)

**Comment by LinusU** [comment]
This seems to be fixed on master, it should probably be closed...
