### ISSUE TITLE
Sleep is passed correctly but always fails as taking too long

### ISSUE THREAD

**Issue by awjrowe** [workshopper/goingnative#70]
I have copied the solution you have and everything is OK but every time I sleep for 111 (correct value passed in) I always get an error along the lines of 

V JavaScript code loads addon and invokes `delay(x, cb)` method
? Slept for the right amount of time (asked for 111ms, slept for 1455)

This is the C++ code

NAN_METHOD(Delay)
{
	int delay = info[0].As<Number>()->IntegerValue();
	Local<Function> callback = info[1].As<Function>();

#ifdef _WIN32
	Sleep(delay);
#else
	usleep(delay * 1000);
#endif

	Nan::MakeCallback(Nan::GetCurrentContext()->Global(), callback, 0, NULL);

	return;
}

I am running on Windows 7 with x64 and I have tried this with node 0.10 and other versions. Is there something that is causing the function not to exit in a timely manner?

**Comment by rvagg** [comment]
How fast is the computer you're using? it's possible that this is simply a thread spin-up time problem for a slower machine.

**Comment by rvagg** [comment]
Also, try again with the latest goingnative and a newer version of Node and you _may_ have more success
