### ISSUE TITLE
Python version is too new v2.6.6

### ISSUE THREAD

**Issue by Rod-O** [workshopper/goingnative#78]
$ goingnative verify
✓ Found usable `node` version: v0.12.7
✓ Found usable `gcc` in $PATH: v4.4.7
✗ `python` version is too new: v2.6.6, please install a version >= v2.6.x and <= v2.7.x
✓ Found usable `node-gyp` in $PATH: v3.6.0

are you kidding??

**Comment by ccarruitero** [comment]
The python verification was refactored in https://github.com/workshopper/goingnative/commit/a0a6eeb62da09fad31d9204af23f6066040d1d1d, so this shouldn't be a problem anymore.
