### ISSUE TITLE
Going native needs a massive upgrade

### ISSUE THREAD

**Issue by inunotaisho26** [workshopper/goingnative#80]
I am one of the mentors of CharmCityJS Node School in Baltimore. We teach once a quarter and most who attend are newbies. Since they are new, they are using the LTS version of Node and, realistically, are not able downgrade to Node 6 in order for this workshop to work. `Going Native` needs to be upgraded to use more recent versions of Node. I have already opened an issue with another workshop, so this needs to be dealt with.

**Comment by ccarruitero** [comment]
fixed by https://github.com/workshopper/goingnative/commit/8e9a0284b2e582b86248a8c45ae22aa41efbb5fc
