### ISSUE TITLE
node version too new using v8.11.3

### ISSUE THREAD

**Issue by tannineo** [workshopper/goingnative#81]
Maybe the workshop can stick to the `LTS` release which is not often changed?  
LTS version has both freshness and reliability.  
The official also recommend it for most of users.  

So the `./exercises/am_i_ready/vars.json` can have the node options like:
```
"node": {
      "min": "8.0.0", // keep the major release
      "max": "8.11.3" // the newest LTS version
},
```

**Comment by 3bute** [comment]
fortunately everyone can manually correct this issue :)

**Comment by ccarruitero** [comment]
fixed by https://github.com/workshopper/goingnative/commit/8e9a0284b2e582b86248a8c45ae22aa41efbb5fc
