### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by retrohacker** [workshopper/goingnative#86]
Heya folks. I don't really maintain this anymore, haven't worked directly with native modules in well over 4 years.

This project doesn't appear to have any other active maintainers and isn't relevant for modern native module development.

Should we be looking for new maintainers? Should we deprecate this? Thoughts?

**Comment by ccarruitero** [comment]
Hi @retrohacker ,

I don't have too much experience with native modules, but I would like to help if possible.

As far I can see in [node docs](https://nodejs.org/api/addons.html), the recommended way to do addons now is to use `N-API`, but still is possible to use nan or internal v8 too. Also, there is [`node-addon-api`](https://github.com/nodejs/node-addon-api) that is the `N-API` headers-only

I think we should have exercises mainly with `N-API`, but having exercises using other options (nan, v8, node-addon-api) would be useful too.

At first step, I think we should evaluate if worth it update this workshop or start a new one.

nan version used is 2.2.0 and current version is 2.14.0, so I think shouldn't be too complicated update the exercises.
Some dependencies package are unmaintained now (like `after` and `map-async`)

So, I suggest to try to update the workshop.
What do you think?

**Comment by retrohacker** [comment]
Thanks for jumping in @ccarruitero!

I'd give you committer rights but I don't have admin rights on this repo. Unless an active maintainer w/ admin rights is around, I think your best bet is to start with a fork of this.

Maybe you can advertise your semi-official fork here on this thread and open a PR to show the improvements?

**Comment by ccarruitero** [comment]
@retrohacker I fixed the current exercises in #84 

Take a look and give any feedback.

I plan to add tests to the repository before start adding exercises with `N-API`, but could be in another PR so is more easy review changes.

I got commit access to the repository :tada:
