### ISSUE TITLE
enable travis for this repository

### ISSUE THREAD

**Issue by ccarruitero** [workshopper/goingnative#88]
I'm trying to add tests for verify solutions #87, but the repository isn't active in travis https://travis-ci.org/github/workshopper/goingnative

Can you enable travis for this repository?

cc @martinheidegger @AnshulMalik

**Comment by martinheidegger** [comment]
Tried to add it to travis but there seems to be a bug. Can we use Github actions instead?

**Comment by AnshulMalik** [comment]
There you go! :)
